require 'totrello'
require 'digest/sha1'

describe 'TrelloCreator' do

  describe 'initialize' do
    it 'should become an instance of itself' do
      t = TrelloCreator.new
      expect(t).to be_an_instance_of(TrelloCreator)
    end

  end

  describe 'create_card' do

    it 'should create a card' do

      directory = "#{Dir.pwd}/test/test_data"
      board_name = directory.split('/').last


      t = TrelloCreator.new

      board = t.find_board(board_name)
      board ||= t.create_board(board_name, 'Auto Generated by ToTrello Gem')

      card_name = {:todo => (Digest::SHA1.hexdigest Time.now.to_s)}
      card = t.create_card(board, card_name, card_name[:todo].reverse,'To Do')
      expect(card).to include(card_name[:todo])

    end

  end

  describe 'find_cards' do

    it 'should find cards' do

      directory = "#{Dir.pwd}/test/test_data"
      board_name = directory.split('/').last


      t = TrelloCreator.new

      board = t.find_board(board_name)
      board ||= t.create_board(board_name, 'Auto Generated by ToTrello Gem')
      list = t.find_list(board, 'To Do')

      cards = t.find_cards(board,list)
      expect(cards).to be_a(Array)

    end

  end


end



