require "totrello/version"
require 'trello_creator'
require 'to_do_find'
require 'totrello_config'


module Totrello

  class Trelloize
    @trello
    @directory
    @config

    def initialize(directory)
      begin
        @trello = TrelloCreator.new
        @directory = directory
        @config = TotrelloConfig.new.read_config
      rescue
        error_data =  "It looks like you're missing some details:\n\n\n"
        error_data += "   You must define TRELLO_DEVELOPER_PUBLIC_KEY & TRELLO_MEMBER_TOKEN\n"
        error_data += "   \nYou can generate the TRELLO_DEVELOPER_PUBLIC_KEY at:\n"
        error_data += "        \nhttps://trello.com/1/appKey/generate\n"
        error_data += "   \nYou can generate the TRELLO_MEMBER_TOKEN at:\n "
        error_data += "\nhttps://trello.com/1/authorize?key=[TRELLO_DEVELOPER_PUBLIC_KEY]&name=ToTrelloGem&expiration=never&response_type=token&scope=read,write\n"
        #raise CustomException.new(error: error_data)
      end

      #find_todo_items
    end

    def find_todo_items
      puts 'Finding your todo items... This should take a minute...'
      todo = ToDoFind.new
      todos = todo.search(@directory, @config[:excludes])
      puts "Woot! We've got'em"

      puts 'Generating your board'

      board_name = !@config[:board_name].nil? ? @config[:board_name] : @directory.split('/').last
      list_name  = !@config[:list].nil? ? @config[:list] : 'To Do'
      puts "Creating the board: #{board_name}"


      board = create_or_gen_board(board_name)

      return -1 if board.nil?

      puts "Created or found a board with the ID: #{board.name}"

      puts 'Talking to Trello, this is the longest part...'
      todos[:todo_list].each do |tdl|
        tdl[:todos].each do |td|
          unless td == ''
            create_trello_card(board, list_name, td, tdl[:file])
          end
        end
      end
      puts "And you're ready to go!"
    end

    def create_or_gen_board(board_name)
      board = @trello.find_board(board_name)
      board ||= @trello.create_board(board_name, 'Auto Generated by ToTrello Gem')
    end

    def create_trello_card(board, list, todo, filename)
      project_name  = !@config[:project_name].nil? ? @config[:project_name] : @directory.split('/').last
      @trello.create_card(board, todo, gen_description(filename,todo, project_name),list)
    end


    def gen_description(file, todo, project_name)
      out =  "TODO item found by ToTrello\n"
      out += "Project name #{project_name}"
      out += "Filename: #{file}\n"
      out += "Action item: #{todo[:todo]}\n"
      out += "Location (at or near) line: #{todo[:location]}\n"
    end


  end


end
